# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import movie_pb2 as movie__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in movie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterMovie = channel.unary_unary(
                '/demo.MovieService/RegisterMovie',
                request_serializer=movie__pb2.Movie.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                _registered_method=True)
        self.SearchMovie = channel.unary_unary(
                '/demo.MovieService/SearchMovie',
                request_serializer=movie__pb2.MovieId.SerializeToString,
                response_deserializer=movie__pb2.Movie.FromString,
                _registered_method=True)
        self.UpdateMovie = channel.unary_unary(
                '/demo.MovieService/UpdateMovie',
                request_serializer=movie__pb2.Movie.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                _registered_method=True)
        self.DeleteMovie = channel.unary_unary(
                '/demo.MovieService/DeleteMovie',
                request_serializer=movie__pb2.MovieId.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                _registered_method=True)


class MovieServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterMovie,
                    request_deserializer=movie__pb2.Movie.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
            'SearchMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMovie,
                    request_deserializer=movie__pb2.MovieId.FromString,
                    response_serializer=movie__pb2.Movie.SerializeToString,
            ),
            'UpdateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovie,
                    request_deserializer=movie__pb2.Movie.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
            'DeleteMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovie,
                    request_deserializer=movie__pb2.MovieId.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'demo.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('demo.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.MovieService/RegisterMovie',
            movie__pb2.Movie.SerializeToString,
            movie__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.MovieService/SearchMovie',
            movie__pb2.MovieId.SerializeToString,
            movie__pb2.Movie.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.MovieService/UpdateMovie',
            movie__pb2.Movie.SerializeToString,
            movie__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/demo.MovieService/DeleteMovie',
            movie__pb2.MovieId.SerializeToString,
            movie__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
