# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: movie.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\x12\x04\x64\x65mo\"L\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\r\n\x05score\x18\x05 \x01(\x05\"\x15\n\x07MovieId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2\xc1\x01\n\x0cMovieService\x12,\n\rRegisterMovie\x12\x0b.demo.Movie\x1a\x0e.demo.Response\x12)\n\x0bSearchMovie\x12\r.demo.MovieId\x1a\x0b.demo.Movie\x12*\n\x0bUpdateMovie\x12\x0b.demo.Movie\x1a\x0e.demo.Response\x12,\n\x0b\x44\x65leteMovie\x12\r.demo.MovieId\x1a\x0e.demo.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIE']._serialized_start=21
  _globals['_MOVIE']._serialized_end=97
  _globals['_MOVIEID']._serialized_start=99
  _globals['_MOVIEID']._serialized_end=120
  _globals['_RESPONSE']._serialized_start=122
  _globals['_RESPONSE']._serialized_end=150
  _globals['_MOVIESERVICE']._serialized_start=153
  _globals['_MOVIESERVICE']._serialized_end=346
# @@protoc_insertion_point(module_scope)
